#pragma once

#include "./lobject.h"
#include "./lapi.h"
typedef unsigned int UINT;

/*
** basic types
*/
#define LUA_TNONE		(-1)

#define LUA_TNIL		0
#define LUA_TBOOLEAN		1
#define LUA_TLIGHTUSERDATA	2
#define LUA_TNUMBER		3
#define LUA_TSTRING		4
#define LUA_TTABLE		5
#define LUA_TFUNCTION		6
#define LUA_TUSERDATA		7
#define LUA_TTHREAD		8

//  Warcraft Types
#define LUA_TAGENT
#define LUA_TEVENT
#define LUA_TPLAYER
#define LUA_TWIDGET
#define LUA_TUNIT
#define LUA_TDESTRUCTABLE
#define LUA_TITEM
#define LUA_TABILITY
#define LUA_TBUFF
#define LUA_TFORCE
#define LUA_TGROUP
#define LUA_TTRIGGER
#define LUA_TTRIGGERCONDITION   
#define LUA_TTRIGGERACTION
#define LUA_TTIMER
#define LUA_TLOCATION
#define LUA_TREGION
#define LUA_TRECT
#define LUA_TBOOLEXPR
#define LUA_TSOUND
#define LUA_TCONDITIONFUNC
#define LUA_TFILTERFUNC
#define LUA_TUNITPOOL
#define LUA_TITEMPOOL
#define LUA_TRACE
#define LUA_TALLIANCETYPE
#define LUA_TRACEPREFERENCE
#define LUA_TGAMESTATE
#define LUA_TIGAMESTATE
#define LUA_TFGAMESTATE
#define LUA_TPLAYERSTATE
#define LUA_TPLAYERSCORE
#define LUA_TPLAYERGAMERESULT
#define LUA_TUNITSTATE
#define LUA_TAIDIFFICULTY

#define LUA_TEVENTID
#define LUA_TGAMEEVENT
#define LUA_TPLAYEREVENT
#define LUA_TPLAYERUNITEVENT
#define LUA_TUNITEVENT
#define LUA_TLIMITOP
#define LUA_TWIDGETEVENT
#define LUA_TDIALOGEVENT
#define LUA_TUNITTYPE

#define LUA_TGAMESPEED
#define LUA_TGAMEDIFFICULTY
#define LUA_TGAMETYPE
#define LUA_TMAPFLAG
#define LUA_TMAPVISIBILITY
#define LUA_TMAPSETTING
#define LUA_TMAPDENSITY
#define LUA_TMAPCONTROL
#define LUA_TPLAYERSLOTSTATE
#define LUA_TVOLUMEGROUP
#define LUA_TCAMERAFIELD
#define LUA_TCAMERASETUP
#define LUA_TPLAYERCOLOR
#define LUA_TPLACEMENT
#define LUA_TSTARTLOCPRIO
#define LUA_TRARITYCONTROL
#define LUA_TBLENDMODE
#define LUA_TTEXMAPFLAGS
#define LUA_TEFFECT
#define LUA_TEFFECTTYPE
#define LUA_TWEATHEREFFECT
#define LUA_TTERRAINDEFORMATION
#define LUA_TFOGSTATE
#define LUA_TFOGMODIFIER
#define LUA_TDIALOG
#define LUA_TBUTTON
#define LUA_TQUEST
#define LUA_TQUESTITEM
#define LUA_TDEFEATCONDITION
#define LUA_TTIMERDIALOG
#define LUA_TLEADERBOARD
#define LUA_TMULTIBOARD
#define LUA_TMULTIBOARDITEM
#define LUA_TTRACKABLE
#define LUA_TGAMECACHE
#define LUA_TVERSION
#define LUA_TITEMTYPE
#define LUA_TTEXTTAG
#define LUA_TATTACKTYPE
#define LUA_TDAMAGETYPE
#define LUA_TWEAPONTYPE
#define LUA_TSOUNDTYPE
#define LUA_TLIGHTNING
#define LUA_TPATHINGTYPE
#define LUA_TIMAGE
#define LUA_TUBERSPLAT
#define LUA_THASHTABLE

#define LUA_NUMTYPES		9 // default 9

#define setvalue(obj,x,t) \
  { TValue *io=(obj); val_(io).i=(x); settt_(io, makevariant(t, 0)); }