local jn = require "jass.natives"

FALSE                                                     = false
TRUE                                                      = true
JASS_MAX_ARRAY_SIZE                                       = 32768
PLAYER_COLOR_RED                                          = jn.ConvertPlayerColor(0)
PLAYER_COLOR_BLUE                                         = jn.ConvertPlayerColor(1)
PLAYER_COLOR_CYAN                                         = jn.ConvertPlayerColor(2)
PLAYER_COLOR_PURPLE                                       = jn.ConvertPlayerColor(3)
PLAYER_COLOR_YELLOW                                       = jn.ConvertPlayerColor(4)
PLAYER_COLOR_ORANGE                                       = jn.ConvertPlayerColor(5)
PLAYER_COLOR_GREEN                                        = jn.ConvertPlayerColor(6)
PLAYER_COLOR_PINK                                         = jn.ConvertPlayerColor(7)
PLAYER_COLOR_LIGHT_GRAY                                   = jn.ConvertPlayerColor(8)
PLAYER_COLOR_LIGHT_BLUE                                   = jn.ConvertPlayerColor(9)
PLAYER_COLOR_AQUA                                         = jn.ConvertPlayerColor(10)
PLAYER_COLOR_BROWN                                        = jn.ConvertPlayerColor(11)
RACE_HUMAN                                                = jn.ConvertRace(1)
RACE_ORC                                                  = jn.ConvertRace(2)
RACE_UNDEAD                                               = jn.ConvertRace(3)
RACE_NIGHTELF                                             = jn.ConvertRace(4)
RACE_DEMON                                                = jn.ConvertRace(5)
RACE_OTHER                                                = jn.ConvertRace(7)
PLAYER_GAME_RESULT_VICTORY                                = jn.ConvertPlayerGameResult(0)
PLAYER_GAME_RESULT_DEFEAT                                 = jn.ConvertPlayerGameResult(1)
PLAYER_GAME_RESULT_TIE                                    = jn.ConvertPlayerGameResult(2)
PLAYER_GAME_RESULT_NEUTRAL                                = jn.ConvertPlayerGameResult(3)
ALLIANCE_PASSIVE                                          = jn.ConvertAllianceType(0)
ALLIANCE_HELP_REQUEST                                     = jn.ConvertAllianceType(1)
ALLIANCE_HELP_RESPONSE                                    = jn.ConvertAllianceType(2)
ALLIANCE_SHARED_XP                                        = jn.ConvertAllianceType(3)
ALLIANCE_SHARED_SPELLS                                    = jn.ConvertAllianceType(4)
ALLIANCE_SHARED_VISION                                    = jn.ConvertAllianceType(5)
ALLIANCE_SHARED_CONTROL                                   = jn.ConvertAllianceType(6)
ALLIANCE_SHARED_ADVANCED_CONTROL                          = jn.ConvertAllianceType(7)
ALLIANCE_RESCUABLE                                        = jn.ConvertAllianceType(8)
ALLIANCE_SHARED_VISION_FORCED                             = jn.ConvertAllianceType(9)
VERSION_REIGN_OF_CHAOS                                    = jn.ConvertVersion(0)
VERSION_FROZEN_THRONE                                     = jn.ConvertVersion(1)
ATTACK_TYPE_NORMAL                                        = jn.ConvertAttackType(0)
ATTACK_TYPE_MELEE                                         = jn.ConvertAttackType(1)
ATTACK_TYPE_PIERCE                                        = jn.ConvertAttackType(2)
ATTACK_TYPE_SIEGE                                         = jn.ConvertAttackType(3)
ATTACK_TYPE_MAGIC                                         = jn.ConvertAttackType(4)
ATTACK_TYPE_CHAOS                                         = jn.ConvertAttackType(5)
ATTACK_TYPE_HERO                                          = jn.ConvertAttackType(6)
DAMAGE_TYPE_UNKNOWN                                       = jn.ConvertDamageType(0)
DAMAGE_TYPE_NORMAL                                        = jn.ConvertDamageType(4)
DAMAGE_TYPE_ENHANCED                                      = jn.ConvertDamageType(5)
DAMAGE_TYPE_FIRE                                          = jn.ConvertDamageType(8)
DAMAGE_TYPE_COLD                                          = jn.ConvertDamageType(9)
DAMAGE_TYPE_LIGHTNING                                     = jn.ConvertDamageType(10)
DAMAGE_TYPE_POISON                                        = jn.ConvertDamageType(11)
DAMAGE_TYPE_DISEASE                                       = jn.ConvertDamageType(12)
DAMAGE_TYPE_DIVINE                                        = jn.ConvertDamageType(13)
DAMAGE_TYPE_MAGIC                                         = jn.ConvertDamageType(14)
DAMAGE_TYPE_SONIC                                         = jn.ConvertDamageType(15)
DAMAGE_TYPE_ACID                                          = jn.ConvertDamageType(16)
DAMAGE_TYPE_FORCE                                         = jn.ConvertDamageType(17)
DAMAGE_TYPE_DEATH                                         = jn.ConvertDamageType(18)
DAMAGE_TYPE_MIND                                          = jn.ConvertDamageType(19)
DAMAGE_TYPE_PLANT                                         = jn.ConvertDamageType(20)
DAMAGE_TYPE_DEFENSIVE                                     = jn.ConvertDamageType(21)
DAMAGE_TYPE_DEMOLITION                                    = jn.ConvertDamageType(22)
DAMAGE_TYPE_SLOW_POISON                                   = jn.ConvertDamageType(23)
DAMAGE_TYPE_SPIRIT_LINK                                   = jn.ConvertDamageType(24)
DAMAGE_TYPE_SHADOW_STRIKE                                 = jn.ConvertDamageType(25)
DAMAGE_TYPE_UNIVERSAL                                     = jn.ConvertDamageType(26)
WEAPON_TYPE_WHOKNOWS                                      = jn.ConvertWeaponType(0)
WEAPON_TYPE_METAL_LIGHT_CHOP                              = jn.ConvertWeaponType(1)
WEAPON_TYPE_METAL_MEDIUM_CHOP                             = jn.ConvertWeaponType(2)
WEAPON_TYPE_METAL_HEAVY_CHOP                              = jn.ConvertWeaponType(3)
WEAPON_TYPE_METAL_LIGHT_SLICE                             = jn.ConvertWeaponType(4)
WEAPON_TYPE_METAL_MEDIUM_SLICE                            = jn.ConvertWeaponType(5)
WEAPON_TYPE_METAL_HEAVY_SLICE                             = jn.ConvertWeaponType(6)
WEAPON_TYPE_METAL_MEDIUM_BASH                             = jn.ConvertWeaponType(7)
WEAPON_TYPE_METAL_HEAVY_BASH                              = jn.ConvertWeaponType(8)
WEAPON_TYPE_METAL_MEDIUM_STAB                             = jn.ConvertWeaponType(9)
WEAPON_TYPE_METAL_HEAVY_STAB                              = jn.ConvertWeaponType(10)
WEAPON_TYPE_WOOD_LIGHT_SLICE                              = jn.ConvertWeaponType(11)
WEAPON_TYPE_WOOD_MEDIUM_SLICE                             = jn.ConvertWeaponType(12)
WEAPON_TYPE_WOOD_HEAVY_SLICE                              = jn.ConvertWeaponType(13)
WEAPON_TYPE_WOOD_LIGHT_BASH                               = jn.ConvertWeaponType(14)
WEAPON_TYPE_WOOD_MEDIUM_BASH                              = jn.ConvertWeaponType(15)
WEAPON_TYPE_WOOD_HEAVY_BASH                               = jn.ConvertWeaponType(16)
WEAPON_TYPE_WOOD_LIGHT_STAB                               = jn.ConvertWeaponType(17)
WEAPON_TYPE_WOOD_MEDIUM_STAB                              = jn.ConvertWeaponType(18)
WEAPON_TYPE_CLAW_LIGHT_SLICE                              = jn.ConvertWeaponType(19)
WEAPON_TYPE_CLAW_MEDIUM_SLICE                             = jn.ConvertWeaponType(20)
WEAPON_TYPE_CLAW_HEAVY_SLICE                              = jn.ConvertWeaponType(21)
WEAPON_TYPE_AXE_MEDIUM_CHOP                               = jn.ConvertWeaponType(22)
WEAPON_TYPE_ROCK_HEAVY_BASH                               = jn.ConvertWeaponType(23)
PATHING_TYPE_ANY                                          = jn.ConvertPathingType(0)
PATHING_TYPE_WALKABILITY                                  = jn.ConvertPathingType(1)
PATHING_TYPE_FLYABILITY                                   = jn.ConvertPathingType(2)
PATHING_TYPE_BUILDABILITY                                 = jn.ConvertPathingType(3)
PATHING_TYPE_PEONHARVESTPATHING                           = jn.ConvertPathingType(4)
PATHING_TYPE_BLIGHTPATHING                                = jn.ConvertPathingType(5)
PATHING_TYPE_FLOATABILITY                                 = jn.ConvertPathingType(6)
PATHING_TYPE_AMPHIBIOUSPATHING                            = jn.ConvertPathingType(7)

-- ===================================================
--  Map Setup Constants
-- ===================================================
RACE_PREF_HUMAN                                           = jn.ConvertRacePref(1)
RACE_PREF_ORC                                             = jn.ConvertRacePref(2)
RACE_PREF_NIGHTELF                                        = jn.ConvertRacePref(4)
RACE_PREF_UNDEAD                                          = jn.ConvertRacePref(8)
RACE_PREF_DEMON                                           = jn.ConvertRacePref(16)
RACE_PREF_RANDOM                                          = jn.ConvertRacePref(32)
RACE_PREF_USER_SELECTABLE                                 = jn.ConvertRacePref(64)
MAP_CONTROL_USER                                          = jn.ConvertMapControl(0)
MAP_CONTROL_COMPUTER                                      = jn.ConvertMapControl(1)
MAP_CONTROL_RESCUABLE                                     = jn.ConvertMapControl(2)
MAP_CONTROL_NEUTRAL                                       = jn.ConvertMapControl(3)
MAP_CONTROL_CREEP                                         = jn.ConvertMapControl(4)
MAP_CONTROL_NONE                                          = jn.ConvertMapControl(5)
GAME_TYPE_MELEE                                           = jn.ConvertGameType(1)
GAME_TYPE_FFA                                             = jn.ConvertGameType(2)
GAME_TYPE_USE_MAP_SETTINGS                                = jn.ConvertGameType(4)
GAME_TYPE_BLIZ                                            = jn.ConvertGameType(8)
GAME_TYPE_ONE_ON_ONE                                      = jn.ConvertGameType(16)
GAME_TYPE_TWO_TEAM_PLAY                                   = jn.ConvertGameType(32)
GAME_TYPE_THREE_TEAM_PLAY                                 = jn.ConvertGameType(64)
GAME_TYPE_FOUR_TEAM_PLAY                                  = jn.ConvertGameType(128)
MAP_FOG_HIDE_TERRAIN                                      = jn.ConvertMapFlag(1)
MAP_FOG_MAP_EXPLORED                                      = jn.ConvertMapFlag(2)
MAP_FOG_ALWAYS_VISIBLE                                    = jn.ConvertMapFlag(4)
MAP_USE_HANDICAPS                                         = jn.ConvertMapFlag(8)
MAP_OBSERVERS                                             = jn.ConvertMapFlag(16)
MAP_OBSERVERS_ON_DEATH                                    = jn.ConvertMapFlag(32)
MAP_FIXED_COLORS                                          = jn.ConvertMapFlag(128)
MAP_LOCK_RESOURCE_TRADING                                 = jn.ConvertMapFlag(256)
MAP_RESOURCE_TRADING_ALLIES_ONLY                          = jn.ConvertMapFlag(512)
MAP_LOCK_ALLIANCE_CHANGES                                 = jn.ConvertMapFlag(1024)
MAP_ALLIANCE_CHANGES_HIDDEN                               = jn.ConvertMapFlag(2048)
MAP_CHEATS                                                = jn.ConvertMapFlag(4096)
MAP_CHEATS_HIDDEN                                         = jn.ConvertMapFlag(8192)
MAP_LOCK_SPEED                                            = jn.ConvertMapFlag(8192 * 2)
MAP_LOCK_RANDOM_SEED                                      = jn.ConvertMapFlag(8192 * 4)
MAP_SHARED_ADVANCED_CONTROL                               = jn.ConvertMapFlag(8192 * 8)
MAP_RANDOM_HERO                                           = jn.ConvertMapFlag(8192 * 16)
MAP_RANDOM_RACES                                          = jn.ConvertMapFlag(8192 * 32)
MAP_RELOADED                                              = jn.ConvertMapFlag(8192 * 64)
MAP_PLACEMENT_RANDOM                                      = jn.ConvertPlacement(0)
MAP_PLACEMENT_FIXED                                       = jn.ConvertPlacement(1)
MAP_PLACEMENT_USE_MAP_SETTINGS                            = jn.ConvertPlacement(2)
MAP_PLACEMENT_TEAMS_TOGETHER                              = jn.ConvertPlacement(3)
MAP_LOC_PRIO_LOW                                          = jn.ConvertStartLocPrio(0)
MAP_LOC_PRIO_HIGH                                         = jn.ConvertStartLocPrio(1)
MAP_LOC_PRIO_NOT                                          = jn.ConvertStartLocPrio(2)
MAP_DENSITY_NONE                                          = jn.ConvertMapDensity(0)
MAP_DENSITY_LIGHT                                         = jn.ConvertMapDensity(1)
MAP_DENSITY_MEDIUM                                        = jn.ConvertMapDensity(2)
MAP_DENSITY_HEAVY                                         = jn.ConvertMapDensity(3)
MAP_DIFFICULTY_EASY                                       = jn.ConvertGameDifficulty(0)
MAP_DIFFICULTY_NORMAL                                     = jn.ConvertGameDifficulty(1)
MAP_DIFFICULTY_HARD                                       = jn.ConvertGameDifficulty(2)
MAP_DIFFICULTY_INSANE                                     = jn.ConvertGameDifficulty(3)
MAP_SPEED_SLOWEST                                         = jn.ConvertGameSpeed(0)
MAP_SPEED_SLOW                                            = jn.ConvertGameSpeed(1)
MAP_SPEED_NORMAL                                          = jn.ConvertGameSpeed(2)
MAP_SPEED_FAST                                            = jn.ConvertGameSpeed(3)
MAP_SPEED_FASTEST                                         = jn.ConvertGameSpeed(4)
PLAYER_SLOT_STATE_EMPTY                                   = jn.ConvertPlayerSlotState(0)
PLAYER_SLOT_STATE_PLAYING                                 = jn.ConvertPlayerSlotState(1)
PLAYER_SLOT_STATE_LEFT                                    = jn.ConvertPlayerSlotState(2)
-- ===================================================
--  Sound Constants
-- ===================================================
SOUND_VOLUMEGROUP_UNITMOVEMENT                            = jn.ConvertVolumeGroup(0)
SOUND_VOLUMEGROUP_UNITSOUNDS                              = jn.ConvertVolumeGroup(1)
SOUND_VOLUMEGROUP_COMBAT                                  = jn.ConvertVolumeGroup(2)
SOUND_VOLUMEGROUP_SPELLS                                  = jn.ConvertVolumeGroup(3)
SOUND_VOLUMEGROUP_UI                                      = jn.ConvertVolumeGroup(4)
SOUND_VOLUMEGROUP_MUSIC                                   = jn.ConvertVolumeGroup(5)
SOUND_VOLUMEGROUP_AMBIENTSOUNDS                           = jn.ConvertVolumeGroup(6)
SOUND_VOLUMEGROUP_FIRE                                    = jn.ConvertVolumeGroup(7)
-- ===================================================
--  Game, Player, and Unit States
--
--  For use with TriggerRegister<X>StateEvent
--
-- ===================================================
GAME_STATE_DIVINE_INTERVENTION                            = jn.ConvertIGameState(0)
GAME_STATE_DISCONNECTED                                   = jn.ConvertIGameState(1)
GAME_STATE_TIME_OF_DAY                                    = jn.ConvertFGameState(2)
PLAYER_STATE_GAME_RESULT                                  = jn.ConvertPlayerState(0)
--  current resource levels
--
PLAYER_STATE_RESOURCE_GOLD                                = jn.ConvertPlayerState(1)
PLAYER_STATE_RESOURCE_LUMBER                              = jn.ConvertPlayerState(2)
PLAYER_STATE_RESOURCE_HERO_TOKENS                         = jn.ConvertPlayerState(3)
PLAYER_STATE_RESOURCE_FOOD_CAP                            = jn.ConvertPlayerState(4)
PLAYER_STATE_RESOURCE_FOOD_USED                           = jn.ConvertPlayerState(5)
PLAYER_STATE_FOOD_CAP_CEILING                             = jn.ConvertPlayerState(6)
PLAYER_STATE_GIVES_BOUNTY                                 = jn.ConvertPlayerState(7)
PLAYER_STATE_ALLIED_VICTORY                               = jn.ConvertPlayerState(8)
PLAYER_STATE_PLACED                                       = jn.ConvertPlayerState(9)
PLAYER_STATE_OBSERVER_ON_DEATH                            = jn.ConvertPlayerState(10)
PLAYER_STATE_OBSERVER                                     = jn.ConvertPlayerState(11)
PLAYER_STATE_UNFOLLOWABLE                                 = jn.ConvertPlayerState(12)
--  taxation rate for each resource
--
PLAYER_STATE_GOLD_UPKEEP_RATE                             = jn.ConvertPlayerState(13)
PLAYER_STATE_LUMBER_UPKEEP_RATE                           = jn.ConvertPlayerState(14)
--  cumulative resources collected by the player during the mission
--
PLAYER_STATE_GOLD_GATHERED                                = jn.ConvertPlayerState(15)
PLAYER_STATE_LUMBER_GATHERED                              = jn.ConvertPlayerState(16)
PLAYER_STATE_NO_CREEP_SLEEP                               = jn.ConvertPlayerState(25)
UNIT_STATE_LIFE                                           = jn.ConvertUnitState(0)
UNIT_STATE_MAX_LIFE                                       = jn.ConvertUnitState(1)
UNIT_STATE_MANA                                           = jn.ConvertUnitState(2)
UNIT_STATE_MAX_MANA                                       = jn.ConvertUnitState(3)
AI_DIFFICULTY_NEWBIE                                      = jn.ConvertAIDifficulty(0)
AI_DIFFICULTY_NORMAL                                      = jn.ConvertAIDifficulty(1)
AI_DIFFICULTY_INSANE                                      = jn.ConvertAIDifficulty(2)
--  player score values
PLAYER_SCORE_UNITS_TRAINED                                = jn.ConvertPlayerScore(0)
PLAYER_SCORE_UNITS_KILLED                                 = jn.ConvertPlayerScore(1)
PLAYER_SCORE_STRUCT_BUILT                                 = jn.ConvertPlayerScore(2)
PLAYER_SCORE_STRUCT_RAZED                                 = jn.ConvertPlayerScore(3)
PLAYER_SCORE_TECH_PERCENT                                 = jn.ConvertPlayerScore(4)
PLAYER_SCORE_FOOD_MAXPROD                                 = jn.ConvertPlayerScore(5)
PLAYER_SCORE_FOOD_MAXUSED                                 = jn.ConvertPlayerScore(6)
PLAYER_SCORE_HEROES_KILLED                                = jn.ConvertPlayerScore(7)
PLAYER_SCORE_ITEMS_GAINED                                 = jn.ConvertPlayerScore(8)
PLAYER_SCORE_MERCS_HIRED                                  = jn.ConvertPlayerScore(9)
PLAYER_SCORE_GOLD_MINED_TOTAL                             = jn.ConvertPlayerScore(10)
PLAYER_SCORE_GOLD_MINED_UPKEEP                            = jn.ConvertPlayerScore(11)
PLAYER_SCORE_GOLD_LOST_UPKEEP                             = jn.ConvertPlayerScore(12)
PLAYER_SCORE_GOLD_LOST_TAX                                = jn.ConvertPlayerScore(13)
PLAYER_SCORE_GOLD_GIVEN                                   = jn.ConvertPlayerScore(14)
PLAYER_SCORE_GOLD_RECEIVED                                = jn.ConvertPlayerScore(15)
PLAYER_SCORE_LUMBER_TOTAL                                 = jn.ConvertPlayerScore(16)
PLAYER_SCORE_LUMBER_LOST_UPKEEP                           = jn.ConvertPlayerScore(17)
PLAYER_SCORE_LUMBER_LOST_TAX                              = jn.ConvertPlayerScore(18)
PLAYER_SCORE_LUMBER_GIVEN                                 = jn.ConvertPlayerScore(19)
PLAYER_SCORE_LUMBER_RECEIVED                              = jn.ConvertPlayerScore(20)
PLAYER_SCORE_UNIT_TOTAL                                   = jn.ConvertPlayerScore(21)
PLAYER_SCORE_HERO_TOTAL                                   = jn.ConvertPlayerScore(22)
PLAYER_SCORE_RESOURCE_TOTAL                               = jn.ConvertPlayerScore(23)
PLAYER_SCORE_TOTAL                                        = jn.ConvertPlayerScore(24)
-- ===================================================
--  Game, Player and Unit Events
--
--   When an event causes a trigger to fire these
--   values allow the action code to determine which
--   event was dispatched and therefore which set of
--   native functions should be used to get information
--   about the event.
--
--  Do NOT change the order or value of these constants
--  without insuring that the JASS_GAME_EVENTS_WAR3 enum
--  is changed to match.
--
-- ===================================================
-- ===================================================
--  For use with TriggerRegisterGameEvent
-- ===================================================
EVENT_GAME_VICTORY                                        = jn.ConvertGameEvent(0)
EVENT_GAME_END_LEVEL                                      = jn.ConvertGameEvent(1)
EVENT_GAME_VARIABLE_LIMIT                                 = jn.ConvertGameEvent(2)
EVENT_GAME_STATE_LIMIT                                    = jn.ConvertGameEvent(3)
EVENT_GAME_TIMER_EXPIRED                                  = jn.ConvertGameEvent(4)
EVENT_GAME_ENTER_REGION                                   = jn.ConvertGameEvent(5)
EVENT_GAME_LEAVE_REGION                                   = jn.ConvertGameEvent(6)
EVENT_GAME_TRACKABLE_HIT                                  = jn.ConvertGameEvent(7)
EVENT_GAME_TRACKABLE_TRACK                                = jn.ConvertGameEvent(8)
EVENT_GAME_SHOW_SKILL                                     = jn.ConvertGameEvent(9)
EVENT_GAME_BUILD_SUBMENU                                  = jn.ConvertGameEvent(10)
-- ===================================================
--  For use with TriggerRegisterPlayerEvent
-- ===================================================
EVENT_PLAYER_STATE_LIMIT                                  = jn.ConvertPlayerEvent(11)
EVENT_PLAYER_ALLIANCE_CHANGED                             = jn.ConvertPlayerEvent(12)
EVENT_PLAYER_DEFEAT                                       = jn.ConvertPlayerEvent(13)
EVENT_PLAYER_VICTORY                                      = jn.ConvertPlayerEvent(14)
EVENT_PLAYER_LEAVE                                        = jn.ConvertPlayerEvent(15)
EVENT_PLAYER_CHAT                                         = jn.ConvertPlayerEvent(16)
EVENT_PLAYER_END_CINEMATIC                                = jn.ConvertPlayerEvent(17)
-- ===================================================
--  For use with TriggerRegisterPlayerUnitEvent
-- ===================================================
EVENT_PLAYER_UNIT_ATTACKED                                = jn.ConvertPlayerUnitEvent(18)
EVENT_PLAYER_UNIT_RESCUED                                 = jn.ConvertPlayerUnitEvent(19)
EVENT_PLAYER_UNIT_DEATH                                   = jn.ConvertPlayerUnitEvent(20)
EVENT_PLAYER_UNIT_DECAY                                   = jn.ConvertPlayerUnitEvent(21)
EVENT_PLAYER_UNIT_DETECTED                                = jn.ConvertPlayerUnitEvent(22)
EVENT_PLAYER_UNIT_HIDDEN                                  = jn.ConvertPlayerUnitEvent(23)
EVENT_PLAYER_UNIT_SELECTED                                = jn.ConvertPlayerUnitEvent(24)
EVENT_PLAYER_UNIT_DESELECTED                              = jn.ConvertPlayerUnitEvent(25)
EVENT_PLAYER_UNIT_CONSTRUCT_START                         = jn.ConvertPlayerUnitEvent(26)
EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL                        = jn.ConvertPlayerUnitEvent(27)
EVENT_PLAYER_UNIT_CONSTRUCT_FINISH                        = jn.ConvertPlayerUnitEvent(28)
EVENT_PLAYER_UNIT_UPGRADE_START                           = jn.ConvertPlayerUnitEvent(29)
EVENT_PLAYER_UNIT_UPGRADE_CANCEL                          = jn.ConvertPlayerUnitEvent(30)
EVENT_PLAYER_UNIT_UPGRADE_FINISH                          = jn.ConvertPlayerUnitEvent(31)
EVENT_PLAYER_UNIT_TRAIN_START                             = jn.ConvertPlayerUnitEvent(32)
EVENT_PLAYER_UNIT_TRAIN_CANCEL                            = jn.ConvertPlayerUnitEvent(33)
EVENT_PLAYER_UNIT_TRAIN_FINISH                            = jn.ConvertPlayerUnitEvent(34)
EVENT_PLAYER_UNIT_RESEARCH_START                          = jn.ConvertPlayerUnitEvent(35)
EVENT_PLAYER_UNIT_RESEARCH_CANCEL                         = jn.ConvertPlayerUnitEvent(36)
EVENT_PLAYER_UNIT_RESEARCH_FINISH                         = jn.ConvertPlayerUnitEvent(37)
EVENT_PLAYER_UNIT_ISSUED_ORDER                            = jn.ConvertPlayerUnitEvent(38)
EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER                      = jn.ConvertPlayerUnitEvent(39)
EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER                     = jn.ConvertPlayerUnitEvent(40)
EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER                       = jn.ConvertPlayerUnitEvent(40)
EVENT_PLAYER_HERO_LEVEL                                   = jn.ConvertPlayerUnitEvent(41)
EVENT_PLAYER_HERO_SKILL                                   = jn.ConvertPlayerUnitEvent(42)
EVENT_PLAYER_HERO_REVIVABLE                               = jn.ConvertPlayerUnitEvent(43)
EVENT_PLAYER_HERO_REVIVE_START                            = jn.ConvertPlayerUnitEvent(44)
EVENT_PLAYER_HERO_REVIVE_CANCEL                           = jn.ConvertPlayerUnitEvent(45)
EVENT_PLAYER_HERO_REVIVE_FINISH                           = jn.ConvertPlayerUnitEvent(46)
EVENT_PLAYER_UNIT_SUMMON                                  = jn.ConvertPlayerUnitEvent(47)
EVENT_PLAYER_UNIT_DROP_ITEM                               = jn.ConvertPlayerUnitEvent(48)
EVENT_PLAYER_UNIT_PICKUP_ITEM                             = jn.ConvertPlayerUnitEvent(49)
EVENT_PLAYER_UNIT_USE_ITEM                                = jn.ConvertPlayerUnitEvent(50)
EVENT_PLAYER_UNIT_LOADED                                  = jn.ConvertPlayerUnitEvent(51)
EVENT_PLAYER_UNIT_DAMAGED                                 = jn.ConvertPlayerUnitEvent(308)
EVENT_PLAYER_UNIT_DAMAGING                                = jn.ConvertPlayerUnitEvent(315)
-- ===================================================
--  For use with TriggerRegisterUnitEvent
-- ===================================================
EVENT_UNIT_DAMAGED                                        = jn.ConvertUnitEvent(52)
EVENT_UNIT_DAMAGING                                       = jn.ConvertUnitEvent(314)
EVENT_UNIT_DEATH                                          = jn.ConvertUnitEvent(53)
EVENT_UNIT_DECAY                                          = jn.ConvertUnitEvent(54)
EVENT_UNIT_DETECTED                                       = jn.ConvertUnitEvent(55)
EVENT_UNIT_HIDDEN                                         = jn.ConvertUnitEvent(56)
EVENT_UNIT_SELECTED                                       = jn.ConvertUnitEvent(57)
EVENT_UNIT_DESELECTED                                     = jn.ConvertUnitEvent(58)
EVENT_UNIT_STATE_LIMIT                                    = jn.ConvertUnitEvent(59)
--  Events which may have a filter for the "other unit"
--
EVENT_UNIT_ACQUIRED_TARGET                                = jn.ConvertUnitEvent(60)
EVENT_UNIT_TARGET_IN_RANGE                                = jn.ConvertUnitEvent(61)
EVENT_UNIT_ATTACKED                                       = jn.ConvertUnitEvent(62)
EVENT_UNIT_RESCUED                                        = jn.ConvertUnitEvent(63)
EVENT_UNIT_CONSTRUCT_CANCEL                               = jn.ConvertUnitEvent(64)
EVENT_UNIT_CONSTRUCT_FINISH                               = jn.ConvertUnitEvent(65)
EVENT_UNIT_UPGRADE_START                                  = jn.ConvertUnitEvent(66)
EVENT_UNIT_UPGRADE_CANCEL                                 = jn.ConvertUnitEvent(67)
EVENT_UNIT_UPGRADE_FINISH                                 = jn.ConvertUnitEvent(68)
--  Events which involve the specified unit performing
--  training of other units
--
EVENT_UNIT_TRAIN_START                                    = jn.ConvertUnitEvent(69)
EVENT_UNIT_TRAIN_CANCEL                                   = jn.ConvertUnitEvent(70)
EVENT_UNIT_TRAIN_FINISH                                   = jn.ConvertUnitEvent(71)
EVENT_UNIT_RESEARCH_START                                 = jn.ConvertUnitEvent(72)
EVENT_UNIT_RESEARCH_CANCEL                                = jn.ConvertUnitEvent(73)
EVENT_UNIT_RESEARCH_FINISH                                = jn.ConvertUnitEvent(74)
EVENT_UNIT_ISSUED_ORDER                                   = jn.ConvertUnitEvent(75)
EVENT_UNIT_ISSUED_POINT_ORDER                             = jn.ConvertUnitEvent(76)
EVENT_UNIT_ISSUED_TARGET_ORDER                            = jn.ConvertUnitEvent(77)
EVENT_UNIT_HERO_LEVEL                                     = jn.ConvertUnitEvent(78)
EVENT_UNIT_HERO_SKILL                                     = jn.ConvertUnitEvent(79)
EVENT_UNIT_HERO_REVIVABLE                                 = jn.ConvertUnitEvent(80)
EVENT_UNIT_HERO_REVIVE_START                              = jn.ConvertUnitEvent(81)
EVENT_UNIT_HERO_REVIVE_CANCEL                             = jn.ConvertUnitEvent(82)
EVENT_UNIT_HERO_REVIVE_FINISH                             = jn.ConvertUnitEvent(83)
EVENT_UNIT_SUMMON                                         = jn.ConvertUnitEvent(84)
EVENT_UNIT_DROP_ITEM                                      = jn.ConvertUnitEvent(85)
EVENT_UNIT_PICKUP_ITEM                                    = jn.ConvertUnitEvent(86)
EVENT_UNIT_USE_ITEM                                       = jn.ConvertUnitEvent(87)
EVENT_UNIT_LOADED                                         = jn.ConvertUnitEvent(88)
EVENT_WIDGET_DEATH                                        = jn.ConvertWidgetEvent(89)
EVENT_DIALOG_BUTTON_CLICK                                 = jn.ConvertDialogEvent(90)
EVENT_DIALOG_CLICK                                        = jn.ConvertDialogEvent(91)
-- ===================================================
--  Frozen Throne Expansion Events
--  Need to be added here to preserve compat
-- ===================================================
-- ===================================================
--  For use with TriggerRegisterGameEvent
-- ===================================================
EVENT_GAME_LOADED                                         = jn.ConvertGameEvent(256)
EVENT_GAME_TOURNAMENT_FINISH_SOON                         = jn.ConvertGameEvent(257)
EVENT_GAME_TOURNAMENT_FINISH_NOW                          = jn.ConvertGameEvent(258)
EVENT_GAME_SAVE                                           = jn.ConvertGameEvent(259)
EVENT_GAME_CUSTOM_UI_FRAME                                = jn.ConvertGameEvent(310)
-- ===================================================
--  For use with TriggerRegisterPlayerEvent
-- ===================================================
EVENT_PLAYER_ARROW_LEFT_DOWN                              = jn.ConvertPlayerEvent(261)
EVENT_PLAYER_ARROW_LEFT_UP                                = jn.ConvertPlayerEvent(262)
EVENT_PLAYER_ARROW_RIGHT_DOWN                             = jn.ConvertPlayerEvent(263)
EVENT_PLAYER_ARROW_RIGHT_UP                               = jn.ConvertPlayerEvent(264)
EVENT_PLAYER_ARROW_DOWN_DOWN                              = jn.ConvertPlayerEvent(265)
EVENT_PLAYER_ARROW_DOWN_UP                                = jn.ConvertPlayerEvent(266)
EVENT_PLAYER_ARROW_UP_DOWN                                = jn.ConvertPlayerEvent(267)
EVENT_PLAYER_ARROW_UP_UP                                  = jn.ConvertPlayerEvent(268)
EVENT_PLAYER_MOUSE_DOWN                                   = jn.ConvertPlayerEvent(305)
EVENT_PLAYER_MOUSE_UP                                     = jn.ConvertPlayerEvent(306)
EVENT_PLAYER_MOUSE_MOVE                                   = jn.ConvertPlayerEvent(307)
EVENT_PLAYER_SYNC_DATA                                    = jn.ConvertPlayerEvent(309)
EVENT_PLAYER_KEY                                          = jn.ConvertPlayerEvent(311)
EVENT_PLAYER_KEY_DOWN                                     = jn.ConvertPlayerEvent(312)
EVENT_PLAYER_KEY_UP                                       = jn.ConvertPlayerEvent(313)
-- ===================================================
--  For use with TriggerRegisterPlayerUnitEvent
-- ===================================================
EVENT_PLAYER_UNIT_SELL                                    = jn.ConvertPlayerUnitEvent(269)
EVENT_PLAYER_UNIT_CHANGE_OWNER                            = jn.ConvertPlayerUnitEvent(270)
EVENT_PLAYER_UNIT_SELL_ITEM                               = jn.ConvertPlayerUnitEvent(271)
EVENT_PLAYER_UNIT_SPELL_CHANNEL                           = jn.ConvertPlayerUnitEvent(272)
EVENT_PLAYER_UNIT_SPELL_CAST                              = jn.ConvertPlayerUnitEvent(273)
EVENT_PLAYER_UNIT_SPELL_EFFECT                            = jn.ConvertPlayerUnitEvent(274)
EVENT_PLAYER_UNIT_SPELL_FINISH                            = jn.ConvertPlayerUnitEvent(275)
EVENT_PLAYER_UNIT_SPELL_ENDCAST                           = jn.ConvertPlayerUnitEvent(276)
EVENT_PLAYER_UNIT_PAWN_ITEM                               = jn.ConvertPlayerUnitEvent(277)
EVENT_PLAYER_UNIT_STACK_ITEM                              = jn.ConvertPlayerUnitEvent(319)
-- ===================================================
--  For use with TriggerRegisterUnitEvent
-- ===================================================
EVENT_UNIT_SELL                                           = jn.ConvertUnitEvent(286)
EVENT_UNIT_CHANGE_OWNER                                   = jn.ConvertUnitEvent(287)
EVENT_UNIT_SELL_ITEM                                      = jn.ConvertUnitEvent(288)
EVENT_UNIT_SPELL_CHANNEL                                  = jn.ConvertUnitEvent(289)
EVENT_UNIT_SPELL_CAST                                     = jn.ConvertUnitEvent(290)
EVENT_UNIT_SPELL_EFFECT                                   = jn.ConvertUnitEvent(291)
EVENT_UNIT_SPELL_FINISH                                   = jn.ConvertUnitEvent(292)
EVENT_UNIT_SPELL_ENDCAST                                  = jn.ConvertUnitEvent(293)
EVENT_UNIT_PAWN_ITEM                                      = jn.ConvertUnitEvent(294)
EVENT_UNIT_STACK_ITEM                                     = jn.ConvertUnitEvent(318)
-- ===================================================
--  Limit Event API constants
--  variable, player state, game state, and unit state events
--  ( do NOT change the order of these... )
-- ===================================================
LESS_THAN                                                 = jn.ConvertLimitOp(0)
LESS_THAN_OR_EQUAL                                        = jn.ConvertLimitOp(1)
EQUAL                                                     = jn.ConvertLimitOp(2)
GREATER_THAN_OR_EQUAL                                     = jn.ConvertLimitOp(3)
GREATER_THAN                                              = jn.ConvertLimitOp(4)
NOT_EQUAL                                                 = jn.ConvertLimitOp(5)
-- ===================================================
--  Unit Type Constants for use with IsUnitType()
-- ===================================================
UNIT_TYPE_HERO                                            = jn.ConvertUnitType(0)
UNIT_TYPE_DEAD                                            = jn.ConvertUnitType(1)
UNIT_TYPE_STRUCTURE                                       = jn.ConvertUnitType(2)
UNIT_TYPE_FLYING                                          = jn.ConvertUnitType(3)
UNIT_TYPE_GROUND                                          = jn.ConvertUnitType(4)
UNIT_TYPE_ATTACKS_FLYING                                  = jn.ConvertUnitType(5)
UNIT_TYPE_ATTACKS_GROUND                                  = jn.ConvertUnitType(6)
UNIT_TYPE_MELEE_ATTACKER                                  = jn.ConvertUnitType(7)
UNIT_TYPE_RANGED_ATTACKER                                 = jn.ConvertUnitType(8)
UNIT_TYPE_GIANT                                           = jn.ConvertUnitType(9)
UNIT_TYPE_SUMMONED                                        = jn.ConvertUnitType(10)
UNIT_TYPE_STUNNED                                         = jn.ConvertUnitType(11)
UNIT_TYPE_PLAGUED                                         = jn.ConvertUnitType(12)
UNIT_TYPE_SNARED                                          = jn.ConvertUnitType(13)
UNIT_TYPE_UNDEAD                                          = jn.ConvertUnitType(14)
UNIT_TYPE_MECHANICAL                                      = jn.ConvertUnitType(15)
UNIT_TYPE_PEON                                            = jn.ConvertUnitType(16)
UNIT_TYPE_SAPPER                                          = jn.ConvertUnitType(17)
UNIT_TYPE_TOWNHALL                                        = jn.ConvertUnitType(18)
UNIT_TYPE_ANCIENT                                         = jn.ConvertUnitType(19)
UNIT_TYPE_TAUREN                                          = jn.ConvertUnitType(20)
UNIT_TYPE_POISONED                                        = jn.ConvertUnitType(21)
UNIT_TYPE_POLYMORPHED                                     = jn.ConvertUnitType(22)
UNIT_TYPE_SLEEPING                                        = jn.ConvertUnitType(23)
UNIT_TYPE_RESISTANT                                       = jn.ConvertUnitType(24)
UNIT_TYPE_ETHEREAL                                        = jn.ConvertUnitType(25)
UNIT_TYPE_MAGIC_IMMUNE                                    = jn.ConvertUnitType(26)
-- ===================================================
--  Unit Type Constants for use with ChooseRandomItemEx()
-- ===================================================
ITEM_TYPE_PERMANENT                                       = jn.ConvertItemType(0)
ITEM_TYPE_CHARGED                                         = jn.ConvertItemType(1)
ITEM_TYPE_POWERUP                                         = jn.ConvertItemType(2)
ITEM_TYPE_ARTIFACT                                        = jn.ConvertItemType(3)
ITEM_TYPE_PURCHASABLE                                     = jn.ConvertItemType(4)
ITEM_TYPE_CAMPAIGN                                        = jn.ConvertItemType(5)
ITEM_TYPE_MISCELLANEOUS                                   = jn.ConvertItemType(6)
ITEM_TYPE_UNKNOWN                                         = jn.ConvertItemType(7)
ITEM_TYPE_ANY                                             = jn.ConvertItemType(8)
--  Deprecated, should use ITEM_TYPE_POWERUP
ITEM_TYPE_TOME                                            = jn.ConvertItemType(2)
-- ===================================================
--  Animatable Camera Fields
-- ===================================================
CAMERA_FIELD_TARGET_DISTANCE                              = jn.ConvertCameraField(0)
CAMERA_FIELD_FARZ                                         = jn.ConvertCameraField(1)
CAMERA_FIELD_ANGLE_OF_ATTACK                              = jn.ConvertCameraField(2)
CAMERA_FIELD_FIELD_OF_VIEW                                = jn.ConvertCameraField(3)
CAMERA_FIELD_ROLL                                         = jn.ConvertCameraField(4)
CAMERA_FIELD_ROTATION                                     = jn.ConvertCameraField(5)
CAMERA_FIELD_ZOFFSET                                      = jn.ConvertCameraField(6)
CAMERA_FIELD_NEARZ                                        = jn.ConvertCameraField(7)
CAMERA_FIELD_LOCAL_PITCH                                  = jn.ConvertCameraField(8)
CAMERA_FIELD_LOCAL_YAW                                    = jn.ConvertCameraField(9)
CAMERA_FIELD_LOCAL_ROLL                                   = jn.ConvertCameraField(10)
BLEND_MODE_NONE                                           = jn.ConvertBlendMode(0)
BLEND_MODE_DONT_CARE                                      = jn.ConvertBlendMode(0)
BLEND_MODE_KEYALPHA                                       = jn.ConvertBlendMode(1)
BLEND_MODE_BLEND                                          = jn.ConvertBlendMode(2)
BLEND_MODE_ADDITIVE                                       = jn.ConvertBlendMode(3)
BLEND_MODE_MODULATE                                       = jn.ConvertBlendMode(4)
BLEND_MODE_MODULATE_2X                                    = jn.ConvertBlendMode(5)
RARITY_FREQUENT                                           = jn.ConvertRarityControl(0)
RARITY_RARE                                               = jn.ConvertRarityControl(1)
TEXMAP_FLAG_NONE                                          = jn.ConvertTexMapFlags(0)
TEXMAP_FLAG_WRAP_U                                        = jn.ConvertTexMapFlags(1)
TEXMAP_FLAG_WRAP_V                                        = jn.ConvertTexMapFlags(2)
TEXMAP_FLAG_WRAP_UV                                       = jn.ConvertTexMapFlags(3)
FOG_OF_WAR_MASKED                                         = jn.ConvertFogState(1)
FOG_OF_WAR_FOGGED                                         = jn.ConvertFogState(2)
FOG_OF_WAR_VISIBLE                                        = jn.ConvertFogState(4)
-- ===================================================
--  Camera Margin constants for use with GetCameraMargin
-- ===================================================
CAMERA_MARGIN_LEFT                                        = 0
CAMERA_MARGIN_RIGHT                                       = 1
CAMERA_MARGIN_TOP                                         = 2
CAMERA_MARGIN_BOTTOM                                      = 3
-- ===================================================
--  Effect API constants
-- ===================================================
EFFECT_TYPE_EFFECT                                        = jn.ConvertEffectType(0)
EFFECT_TYPE_TARGET                                        = jn.ConvertEffectType(1)
EFFECT_TYPE_CASTER                                        = jn.ConvertEffectType(2)
EFFECT_TYPE_SPECIAL                                       = jn.ConvertEffectType(3)
EFFECT_TYPE_AREA_EFFECT                                   = jn.ConvertEffectType(4)
EFFECT_TYPE_MISSILE                                       = jn.ConvertEffectType(5)
EFFECT_TYPE_LIGHTNING                                     = jn.ConvertEffectType(6)
SOUND_TYPE_EFFECT                                         = jn.ConvertSoundType(0)
SOUND_TYPE_EFFECT_LOOPED                                  = jn.ConvertSoundType(1)