FALSE                                                     = false
TRUE                                                      = true
JASS_MAX_ARRAY_SIZE                                       = 8192
PLAYER_NEUTRAL_PASSIVE 									  = 15
PLAYER_NEUTRAL_AGGRESSIVE 								  = 12
PLAYER_COLOR_RED                                          = ConvertPlayerColor(0)
PLAYER_COLOR_BLUE                                         = ConvertPlayerColor(1)
PLAYER_COLOR_CYAN                                         = ConvertPlayerColor(2)
PLAYER_COLOR_PURPLE                                       = ConvertPlayerColor(3)
PLAYER_COLOR_YELLOW                                       = ConvertPlayerColor(4)
PLAYER_COLOR_ORANGE                                       = ConvertPlayerColor(5)
PLAYER_COLOR_GREEN                                        = ConvertPlayerColor(6)
PLAYER_COLOR_PINK                                         = ConvertPlayerColor(7)
PLAYER_COLOR_LIGHT_GRAY                                   = ConvertPlayerColor(8)
PLAYER_COLOR_LIGHT_BLUE                                   = ConvertPlayerColor(9)
PLAYER_COLOR_AQUA                                         = ConvertPlayerColor(10)
PLAYER_COLOR_BROWN                                        = ConvertPlayerColor(11)
RACE_HUMAN                                                = ConvertRace(1)
RACE_ORC                                                  = ConvertRace(2)
RACE_UNDEAD                                               = ConvertRace(3)
RACE_NIGHTELF                                             = ConvertRace(4)
RACE_DEMON                                                = ConvertRace(5)
RACE_OTHER                                                = ConvertRace(7)
PLAYER_GAME_RESULT_VICTORY                                = ConvertPlayerGameResult(0)
PLAYER_GAME_RESULT_DEFEAT                                 = ConvertPlayerGameResult(1)
PLAYER_GAME_RESULT_TIE                                    = ConvertPlayerGameResult(2)
PLAYER_GAME_RESULT_NEUTRAL                                = ConvertPlayerGameResult(3)
ALLIANCE_PASSIVE                                          = ConvertAllianceType(0)
ALLIANCE_HELP_REQUEST                                     = ConvertAllianceType(1)
ALLIANCE_HELP_RESPONSE                                    = ConvertAllianceType(2)
ALLIANCE_SHARED_XP                                        = ConvertAllianceType(3)
ALLIANCE_SHARED_SPELLS                                    = ConvertAllianceType(4)
ALLIANCE_SHARED_VISION                                    = ConvertAllianceType(5)
ALLIANCE_SHARED_CONTROL                                   = ConvertAllianceType(6)
ALLIANCE_SHARED_ADVANCED_CONTROL                          = ConvertAllianceType(7)
ALLIANCE_RESCUABLE                                        = ConvertAllianceType(8)
ALLIANCE_SHARED_VISION_FORCED                             = ConvertAllianceType(9)
VERSION_REIGN_OF_CHAOS                                    = ConvertVersion(0)
VERSION_FROZEN_THRONE                                     = ConvertVersion(1)
ATTACK_TYPE_NORMAL                                        = ConvertAttackType(0)
ATTACK_TYPE_MELEE                                         = ConvertAttackType(1)
ATTACK_TYPE_PIERCE                                        = ConvertAttackType(2)
ATTACK_TYPE_SIEGE                                         = ConvertAttackType(3)
ATTACK_TYPE_MAGIC                                         = ConvertAttackType(4)
ATTACK_TYPE_CHAOS                                         = ConvertAttackType(5)
ATTACK_TYPE_HERO                                          = ConvertAttackType(6)
DAMAGE_TYPE_UNKNOWN                                       = ConvertDamageType(0)
DAMAGE_TYPE_NORMAL                                        = ConvertDamageType(4)
DAMAGE_TYPE_ENHANCED                                      = ConvertDamageType(5)
DAMAGE_TYPE_FIRE                                          = ConvertDamageType(8)
DAMAGE_TYPE_COLD                                          = ConvertDamageType(9)
DAMAGE_TYPE_LIGHTNING                                     = ConvertDamageType(10)
DAMAGE_TYPE_POISON                                        = ConvertDamageType(11)
DAMAGE_TYPE_DISEASE                                       = ConvertDamageType(12)
DAMAGE_TYPE_DIVINE                                        = ConvertDamageType(13)
DAMAGE_TYPE_MAGIC                                         = ConvertDamageType(14)
DAMAGE_TYPE_SONIC                                         = ConvertDamageType(15)
DAMAGE_TYPE_ACID                                          = ConvertDamageType(16)
DAMAGE_TYPE_FORCE                                         = ConvertDamageType(17)
DAMAGE_TYPE_DEATH                                         = ConvertDamageType(18)
DAMAGE_TYPE_MIND                                          = ConvertDamageType(19)
DAMAGE_TYPE_PLANT                                         = ConvertDamageType(20)
DAMAGE_TYPE_DEFENSIVE                                     = ConvertDamageType(21)
DAMAGE_TYPE_DEMOLITION                                    = ConvertDamageType(22)
DAMAGE_TYPE_SLOW_POISON                                   = ConvertDamageType(23)
DAMAGE_TYPE_SPIRIT_LINK                                   = ConvertDamageType(24)
DAMAGE_TYPE_SHADOW_STRIKE                                 = ConvertDamageType(25)
DAMAGE_TYPE_UNIVERSAL                                     = ConvertDamageType(26)
WEAPON_TYPE_WHOKNOWS                                      = ConvertWeaponType(0)
WEAPON_TYPE_METAL_LIGHT_CHOP                              = ConvertWeaponType(1)
WEAPON_TYPE_METAL_MEDIUM_CHOP                             = ConvertWeaponType(2)
WEAPON_TYPE_METAL_HEAVY_CHOP                              = ConvertWeaponType(3)
WEAPON_TYPE_METAL_LIGHT_SLICE                             = ConvertWeaponType(4)
WEAPON_TYPE_METAL_MEDIUM_SLICE                            = ConvertWeaponType(5)
WEAPON_TYPE_METAL_HEAVY_SLICE                             = ConvertWeaponType(6)
WEAPON_TYPE_METAL_MEDIUM_BASH                             = ConvertWeaponType(7)
WEAPON_TYPE_METAL_HEAVY_BASH                              = ConvertWeaponType(8)
WEAPON_TYPE_METAL_MEDIUM_STAB                             = ConvertWeaponType(9)
WEAPON_TYPE_METAL_HEAVY_STAB                              = ConvertWeaponType(10)
WEAPON_TYPE_WOOD_LIGHT_SLICE                              = ConvertWeaponType(11)
WEAPON_TYPE_WOOD_MEDIUM_SLICE                             = ConvertWeaponType(12)
WEAPON_TYPE_WOOD_HEAVY_SLICE                              = ConvertWeaponType(13)
WEAPON_TYPE_WOOD_LIGHT_BASH                               = ConvertWeaponType(14)
WEAPON_TYPE_WOOD_MEDIUM_BASH                              = ConvertWeaponType(15)
WEAPON_TYPE_WOOD_HEAVY_BASH                               = ConvertWeaponType(16)
WEAPON_TYPE_WOOD_LIGHT_STAB                               = ConvertWeaponType(17)
WEAPON_TYPE_WOOD_MEDIUM_STAB                              = ConvertWeaponType(18)
WEAPON_TYPE_CLAW_LIGHT_SLICE                              = ConvertWeaponType(19)
WEAPON_TYPE_CLAW_MEDIUM_SLICE                             = ConvertWeaponType(20)
WEAPON_TYPE_CLAW_HEAVY_SLICE                              = ConvertWeaponType(21)
WEAPON_TYPE_AXE_MEDIUM_CHOP                               = ConvertWeaponType(22)
WEAPON_TYPE_ROCK_HEAVY_BASH                               = ConvertWeaponType(23)
PATHING_TYPE_ANY                                          = ConvertPathingType(0)
PATHING_TYPE_WALKABILITY                                  = ConvertPathingType(1)
PATHING_TYPE_FLYABILITY                                   = ConvertPathingType(2)
PATHING_TYPE_BUILDABILITY                                 = ConvertPathingType(3)
PATHING_TYPE_PEONHARVESTPATHING                           = ConvertPathingType(4)
PATHING_TYPE_BLIGHTPATHING                                = ConvertPathingType(5)
PATHING_TYPE_FLOATABILITY                                 = ConvertPathingType(6)
PATHING_TYPE_AMPHIBIOUSPATHING                            = ConvertPathingType(7)

-- ===================================================
--  Map Setup Constants
-- ===================================================
RACE_PREF_HUMAN                                           = ConvertRacePref(1)
RACE_PREF_ORC                                             = ConvertRacePref(2)
RACE_PREF_NIGHTELF                                        = ConvertRacePref(4)
RACE_PREF_UNDEAD                                          = ConvertRacePref(8)
RACE_PREF_DEMON                                           = ConvertRacePref(16)
RACE_PREF_RANDOM                                          = ConvertRacePref(32)
RACE_PREF_USER_SELECTABLE                                 = ConvertRacePref(64)
MAP_CONTROL_USER                                          = ConvertMapControl(0)
MAP_CONTROL_COMPUTER                                      = ConvertMapControl(1)
MAP_CONTROL_RESCUABLE                                     = ConvertMapControl(2)
MAP_CONTROL_NEUTRAL                                       = ConvertMapControl(3)
MAP_CONTROL_CREEP                                         = ConvertMapControl(4)
MAP_CONTROL_NONE                                          = ConvertMapControl(5)
GAME_TYPE_MELEE                                           = ConvertGameType(1)
GAME_TYPE_FFA                                             = ConvertGameType(2)
GAME_TYPE_USE_MAP_SETTINGS                                = ConvertGameType(4)
GAME_TYPE_BLIZ                                            = ConvertGameType(8)
GAME_TYPE_ONE_ON_ONE                                      = ConvertGameType(16)
GAME_TYPE_TWO_TEAM_PLAY                                   = ConvertGameType(32)
GAME_TYPE_THREE_TEAM_PLAY                                 = ConvertGameType(64)
GAME_TYPE_FOUR_TEAM_PLAY                                  = ConvertGameType(128)
MAP_FOG_HIDE_TERRAIN                                      = ConvertMapFlag(1)
MAP_FOG_MAP_EXPLORED                                      = ConvertMapFlag(2)
MAP_FOG_ALWAYS_VISIBLE                                    = ConvertMapFlag(4)
MAP_USE_HANDICAPS                                         = ConvertMapFlag(8)
MAP_OBSERVERS                                             = ConvertMapFlag(16)
MAP_OBSERVERS_ON_DEATH                                    = ConvertMapFlag(32)
MAP_FIXED_COLORS                                          = ConvertMapFlag(128)
MAP_LOCK_RESOURCE_TRADING                                 = ConvertMapFlag(256)
MAP_RESOURCE_TRADING_ALLIES_ONLY                          = ConvertMapFlag(512)
MAP_LOCK_ALLIANCE_CHANGES                                 = ConvertMapFlag(1024)
MAP_ALLIANCE_CHANGES_HIDDEN                               = ConvertMapFlag(2048)
MAP_CHEATS                                                = ConvertMapFlag(4096)
MAP_CHEATS_HIDDEN                                         = ConvertMapFlag(8192)
MAP_LOCK_SPEED                                            = ConvertMapFlag(8192 * 2)
MAP_LOCK_RANDOM_SEED                                      = ConvertMapFlag(8192 * 4)
MAP_SHARED_ADVANCED_CONTROL                               = ConvertMapFlag(8192 * 8)
MAP_RANDOM_HERO                                           = ConvertMapFlag(8192 * 16)
MAP_RANDOM_RACES                                          = ConvertMapFlag(8192 * 32)
MAP_RELOADED                                              = ConvertMapFlag(8192 * 64)
MAP_PLACEMENT_RANDOM                                      = ConvertPlacement(0)
MAP_PLACEMENT_FIXED                                       = ConvertPlacement(1)
MAP_PLACEMENT_USE_MAP_SETTINGS                            = ConvertPlacement(2)
MAP_PLACEMENT_TEAMS_TOGETHER                              = ConvertPlacement(3)
MAP_LOC_PRIO_LOW                                          = ConvertStartLocPrio(0)
MAP_LOC_PRIO_HIGH                                         = ConvertStartLocPrio(1)
MAP_LOC_PRIO_NOT                                          = ConvertStartLocPrio(2)
MAP_DENSITY_NONE                                          = ConvertMapDensity(0)
MAP_DENSITY_LIGHT                                         = ConvertMapDensity(1)
MAP_DENSITY_MEDIUM                                        = ConvertMapDensity(2)
MAP_DENSITY_HEAVY                                         = ConvertMapDensity(3)
MAP_DIFFICULTY_EASY                                       = ConvertGameDifficulty(0)
MAP_DIFFICULTY_NORMAL                                     = ConvertGameDifficulty(1)
MAP_DIFFICULTY_HARD                                       = ConvertGameDifficulty(2)
MAP_DIFFICULTY_INSANE                                     = ConvertGameDifficulty(3)
MAP_SPEED_SLOWEST                                         = ConvertGameSpeed(0)
MAP_SPEED_SLOW                                            = ConvertGameSpeed(1)
MAP_SPEED_NORMAL                                          = ConvertGameSpeed(2)
MAP_SPEED_FAST                                            = ConvertGameSpeed(3)
MAP_SPEED_FASTEST                                         = ConvertGameSpeed(4)
PLAYER_SLOT_STATE_EMPTY                                   = ConvertPlayerSlotState(0)
PLAYER_SLOT_STATE_PLAYING                                 = ConvertPlayerSlotState(1)
PLAYER_SLOT_STATE_LEFT                                    = ConvertPlayerSlotState(2)
-- ===================================================
--  Sound Constants
-- ===================================================
SOUND_VOLUMEGROUP_UNITMOVEMENT                            = ConvertVolumeGroup(0)
SOUND_VOLUMEGROUP_UNITSOUNDS                              = ConvertVolumeGroup(1)
SOUND_VOLUMEGROUP_COMBAT                                  = ConvertVolumeGroup(2)
SOUND_VOLUMEGROUP_SPELLS                                  = ConvertVolumeGroup(3)
SOUND_VOLUMEGROUP_UI                                      = ConvertVolumeGroup(4)
SOUND_VOLUMEGROUP_MUSIC                                   = ConvertVolumeGroup(5)
SOUND_VOLUMEGROUP_AMBIENTSOUNDS                           = ConvertVolumeGroup(6)
SOUND_VOLUMEGROUP_FIRE                                    = ConvertVolumeGroup(7)
-- ===================================================
--  Game, Player, and Unit States
--
--  For use with TriggerRegister<X>StateEvent
--
-- ===================================================
GAME_STATE_DIVINE_INTERVENTION                            = ConvertIGameState(0)
GAME_STATE_DISCONNECTED                                   = ConvertIGameState(1)
GAME_STATE_TIME_OF_DAY                                    = ConvertFGameState(2)
PLAYER_STATE_GAME_RESULT                                  = ConvertPlayerState(0)
--  current resource levels
--
PLAYER_STATE_RESOURCE_GOLD                                = ConvertPlayerState(1)
PLAYER_STATE_RESOURCE_LUMBER                              = ConvertPlayerState(2)
PLAYER_STATE_RESOURCE_HERO_TOKENS                         = ConvertPlayerState(3)
PLAYER_STATE_RESOURCE_FOOD_CAP                            = ConvertPlayerState(4)
PLAYER_STATE_RESOURCE_FOOD_USED                           = ConvertPlayerState(5)
PLAYER_STATE_FOOD_CAP_CEILING                             = ConvertPlayerState(6)
PLAYER_STATE_GIVES_BOUNTY                                 = ConvertPlayerState(7)
PLAYER_STATE_ALLIED_VICTORY                               = ConvertPlayerState(8)
PLAYER_STATE_PLACED                                       = ConvertPlayerState(9)
PLAYER_STATE_OBSERVER_ON_DEATH                            = ConvertPlayerState(10)
PLAYER_STATE_OBSERVER                                     = ConvertPlayerState(11)
PLAYER_STATE_UNFOLLOWABLE                                 = ConvertPlayerState(12)
--  taxation rate for each resource
--
PLAYER_STATE_GOLD_UPKEEP_RATE                             = ConvertPlayerState(13)
PLAYER_STATE_LUMBER_UPKEEP_RATE                           = ConvertPlayerState(14)
--  cumulative resources collected by the player during the mission
--
PLAYER_STATE_GOLD_GATHERED                                = ConvertPlayerState(15)
PLAYER_STATE_LUMBER_GATHERED                              = ConvertPlayerState(16)
PLAYER_STATE_NO_CREEP_SLEEP                               = ConvertPlayerState(25)
UNIT_STATE_LIFE                                           = ConvertUnitState(0)
UNIT_STATE_MAX_LIFE                                       = ConvertUnitState(1)
UNIT_STATE_MANA                                           = ConvertUnitState(2)
UNIT_STATE_MAX_MANA                                       = ConvertUnitState(3)
AI_DIFFICULTY_NEWBIE                                      = ConvertAIDifficulty(0)
AI_DIFFICULTY_NORMAL                                      = ConvertAIDifficulty(1)
AI_DIFFICULTY_INSANE                                      = ConvertAIDifficulty(2)
--  player score values
PLAYER_SCORE_UNITS_TRAINED                                = ConvertPlayerScore(0)
PLAYER_SCORE_UNITS_KILLED                                 = ConvertPlayerScore(1)
PLAYER_SCORE_STRUCT_BUILT                                 = ConvertPlayerScore(2)
PLAYER_SCORE_STRUCT_RAZED                                 = ConvertPlayerScore(3)
PLAYER_SCORE_TECH_PERCENT                                 = ConvertPlayerScore(4)
PLAYER_SCORE_FOOD_MAXPROD                                 = ConvertPlayerScore(5)
PLAYER_SCORE_FOOD_MAXUSED                                 = ConvertPlayerScore(6)
PLAYER_SCORE_HEROES_KILLED                                = ConvertPlayerScore(7)
PLAYER_SCORE_ITEMS_GAINED                                 = ConvertPlayerScore(8)
PLAYER_SCORE_MERCS_HIRED                                  = ConvertPlayerScore(9)
PLAYER_SCORE_GOLD_MINED_TOTAL                             = ConvertPlayerScore(10)
PLAYER_SCORE_GOLD_MINED_UPKEEP                            = ConvertPlayerScore(11)
PLAYER_SCORE_GOLD_LOST_UPKEEP                             = ConvertPlayerScore(12)
PLAYER_SCORE_GOLD_LOST_TAX                                = ConvertPlayerScore(13)
PLAYER_SCORE_GOLD_GIVEN                                   = ConvertPlayerScore(14)
PLAYER_SCORE_GOLD_RECEIVED                                = ConvertPlayerScore(15)
PLAYER_SCORE_LUMBER_TOTAL                                 = ConvertPlayerScore(16)
PLAYER_SCORE_LUMBER_LOST_UPKEEP                           = ConvertPlayerScore(17)
PLAYER_SCORE_LUMBER_LOST_TAX                              = ConvertPlayerScore(18)
PLAYER_SCORE_LUMBER_GIVEN                                 = ConvertPlayerScore(19)
PLAYER_SCORE_LUMBER_RECEIVED                              = ConvertPlayerScore(20)
PLAYER_SCORE_UNIT_TOTAL                                   = ConvertPlayerScore(21)
PLAYER_SCORE_HERO_TOTAL                                   = ConvertPlayerScore(22)
PLAYER_SCORE_RESOURCE_TOTAL                               = ConvertPlayerScore(23)
PLAYER_SCORE_TOTAL                                        = ConvertPlayerScore(24)
-- ===================================================
--  Game, Player and Unit Events
--
--   When an event causes a trigger to fire these
--   values allow the action code to determine which
--   event was dispatched and therefore which set of
--   native functions should be used to get information
--   about the event.
--
--  Do NOT change the order or value of these constants
--  without insuring that the JASS_GAME_EVENTS_WAR3 enum
--  is changed to match.
--
-- ===================================================
-- ===================================================
--  For use with TriggerRegisterGameEvent
-- ===================================================
EVENT_GAME_VICTORY                                        = ConvertGameEvent(0)
EVENT_GAME_END_LEVEL                                      = ConvertGameEvent(1)
EVENT_GAME_VARIABLE_LIMIT                                 = ConvertGameEvent(2)
EVENT_GAME_STATE_LIMIT                                    = ConvertGameEvent(3)
EVENT_GAME_TIMER_EXPIRED                                  = ConvertGameEvent(4)
EVENT_GAME_ENTER_REGION                                   = ConvertGameEvent(5)
EVENT_GAME_LEAVE_REGION                                   = ConvertGameEvent(6)
EVENT_GAME_TRACKABLE_HIT                                  = ConvertGameEvent(7)
EVENT_GAME_TRACKABLE_TRACK                                = ConvertGameEvent(8)
EVENT_GAME_SHOW_SKILL                                     = ConvertGameEvent(9)
EVENT_GAME_BUILD_SUBMENU                                  = ConvertGameEvent(10)
-- ===================================================
--  For use with TriggerRegisterPlayerEvent
-- ===================================================
EVENT_PLAYER_STATE_LIMIT                                  = ConvertPlayerEvent(11)
EVENT_PLAYER_ALLIANCE_CHANGED                             = ConvertPlayerEvent(12)
EVENT_PLAYER_DEFEAT                                       = ConvertPlayerEvent(13)
EVENT_PLAYER_VICTORY                                      = ConvertPlayerEvent(14)
EVENT_PLAYER_LEAVE                                        = ConvertPlayerEvent(15)
EVENT_PLAYER_CHAT                                         = ConvertPlayerEvent(16)
EVENT_PLAYER_END_CINEMATIC                                = ConvertPlayerEvent(17)
-- ===================================================
--  For use with TriggerRegisterPlayerUnitEvent
-- ===================================================
EVENT_PLAYER_UNIT_ATTACKED                                = ConvertPlayerUnitEvent(18)
EVENT_PLAYER_UNIT_RESCUED                                 = ConvertPlayerUnitEvent(19)
EVENT_PLAYER_UNIT_DEATH                                   = ConvertPlayerUnitEvent(20)
EVENT_PLAYER_UNIT_DECAY                                   = ConvertPlayerUnitEvent(21)
EVENT_PLAYER_UNIT_DETECTED                                = ConvertPlayerUnitEvent(22)
EVENT_PLAYER_UNIT_HIDDEN                                  = ConvertPlayerUnitEvent(23)
EVENT_PLAYER_UNIT_SELECTED                                = ConvertPlayerUnitEvent(24)
EVENT_PLAYER_UNIT_DESELECTED                              = ConvertPlayerUnitEvent(25)
EVENT_PLAYER_UNIT_CONSTRUCT_START                         = ConvertPlayerUnitEvent(26)
EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL                        = ConvertPlayerUnitEvent(27)
EVENT_PLAYER_UNIT_CONSTRUCT_FINISH                        = ConvertPlayerUnitEvent(28)
EVENT_PLAYER_UNIT_UPGRADE_START                           = ConvertPlayerUnitEvent(29)
EVENT_PLAYER_UNIT_UPGRADE_CANCEL                          = ConvertPlayerUnitEvent(30)
EVENT_PLAYER_UNIT_UPGRADE_FINISH                          = ConvertPlayerUnitEvent(31)
EVENT_PLAYER_UNIT_TRAIN_START                             = ConvertPlayerUnitEvent(32)
EVENT_PLAYER_UNIT_TRAIN_CANCEL                            = ConvertPlayerUnitEvent(33)
EVENT_PLAYER_UNIT_TRAIN_FINISH                            = ConvertPlayerUnitEvent(34)
EVENT_PLAYER_UNIT_RESEARCH_START                          = ConvertPlayerUnitEvent(35)
EVENT_PLAYER_UNIT_RESEARCH_CANCEL                         = ConvertPlayerUnitEvent(36)
EVENT_PLAYER_UNIT_RESEARCH_FINISH                         = ConvertPlayerUnitEvent(37)
EVENT_PLAYER_UNIT_ISSUED_ORDER                            = ConvertPlayerUnitEvent(38)
EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER                      = ConvertPlayerUnitEvent(39)
EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER                     = ConvertPlayerUnitEvent(40)
EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER                       = ConvertPlayerUnitEvent(40)
EVENT_PLAYER_HERO_LEVEL                                   = ConvertPlayerUnitEvent(41)
EVENT_PLAYER_HERO_SKILL                                   = ConvertPlayerUnitEvent(42)
EVENT_PLAYER_HERO_REVIVABLE                               = ConvertPlayerUnitEvent(43)
EVENT_PLAYER_HERO_REVIVE_START                            = ConvertPlayerUnitEvent(44)
EVENT_PLAYER_HERO_REVIVE_CANCEL                           = ConvertPlayerUnitEvent(45)
EVENT_PLAYER_HERO_REVIVE_FINISH                           = ConvertPlayerUnitEvent(46)
EVENT_PLAYER_UNIT_SUMMON                                  = ConvertPlayerUnitEvent(47)
EVENT_PLAYER_UNIT_DROP_ITEM                               = ConvertPlayerUnitEvent(48)
EVENT_PLAYER_UNIT_PICKUP_ITEM                             = ConvertPlayerUnitEvent(49)
EVENT_PLAYER_UNIT_USE_ITEM                                = ConvertPlayerUnitEvent(50)
EVENT_PLAYER_UNIT_LOADED                                  = ConvertPlayerUnitEvent(51)
EVENT_PLAYER_UNIT_DAMAGED                                 = ConvertPlayerUnitEvent(308)
EVENT_PLAYER_UNIT_DAMAGING                                = ConvertPlayerUnitEvent(315)
-- ===================================================
--  For use with TriggerRegisterUnitEvent
-- ===================================================
EVENT_UNIT_DAMAGED                                        = ConvertUnitEvent(52)
EVENT_UNIT_DAMAGING                                       = ConvertUnitEvent(314)
EVENT_UNIT_DEATH                                          = ConvertUnitEvent(53)
EVENT_UNIT_DECAY                                          = ConvertUnitEvent(54)
EVENT_UNIT_DETECTED                                       = ConvertUnitEvent(55)
EVENT_UNIT_HIDDEN                                         = ConvertUnitEvent(56)
EVENT_UNIT_SELECTED                                       = ConvertUnitEvent(57)
EVENT_UNIT_DESELECTED                                     = ConvertUnitEvent(58)
EVENT_UNIT_STATE_LIMIT                                    = ConvertUnitEvent(59)
--  Events which may have a filter for the "other unit"
--
EVENT_UNIT_ACQUIRED_TARGET                                = ConvertUnitEvent(60)
EVENT_UNIT_TARGET_IN_RANGE                                = ConvertUnitEvent(61)
EVENT_UNIT_ATTACKED                                       = ConvertUnitEvent(62)
EVENT_UNIT_RESCUED                                        = ConvertUnitEvent(63)
EVENT_UNIT_CONSTRUCT_CANCEL                               = ConvertUnitEvent(64)
EVENT_UNIT_CONSTRUCT_FINISH                               = ConvertUnitEvent(65)
EVENT_UNIT_UPGRADE_START                                  = ConvertUnitEvent(66)
EVENT_UNIT_UPGRADE_CANCEL                                 = ConvertUnitEvent(67)
EVENT_UNIT_UPGRADE_FINISH                                 = ConvertUnitEvent(68)
--  Events which involve the specified unit performing
--  training of other units
--
EVENT_UNIT_TRAIN_START                                    = ConvertUnitEvent(69)
EVENT_UNIT_TRAIN_CANCEL                                   = ConvertUnitEvent(70)
EVENT_UNIT_TRAIN_FINISH                                   = ConvertUnitEvent(71)
EVENT_UNIT_RESEARCH_START                                 = ConvertUnitEvent(72)
EVENT_UNIT_RESEARCH_CANCEL                                = ConvertUnitEvent(73)
EVENT_UNIT_RESEARCH_FINISH                                = ConvertUnitEvent(74)
EVENT_UNIT_ISSUED_ORDER                                   = ConvertUnitEvent(75)
EVENT_UNIT_ISSUED_POINT_ORDER                             = ConvertUnitEvent(76)
EVENT_UNIT_ISSUED_TARGET_ORDER                            = ConvertUnitEvent(77)
EVENT_UNIT_HERO_LEVEL                                     = ConvertUnitEvent(78)
EVENT_UNIT_HERO_SKILL                                     = ConvertUnitEvent(79)
EVENT_UNIT_HERO_REVIVABLE                                 = ConvertUnitEvent(80)
EVENT_UNIT_HERO_REVIVE_START                              = ConvertUnitEvent(81)
EVENT_UNIT_HERO_REVIVE_CANCEL                             = ConvertUnitEvent(82)
EVENT_UNIT_HERO_REVIVE_FINISH                             = ConvertUnitEvent(83)
EVENT_UNIT_SUMMON                                         = ConvertUnitEvent(84)
EVENT_UNIT_DROP_ITEM                                      = ConvertUnitEvent(85)
EVENT_UNIT_PICKUP_ITEM                                    = ConvertUnitEvent(86)
EVENT_UNIT_USE_ITEM                                       = ConvertUnitEvent(87)
EVENT_UNIT_LOADED                                         = ConvertUnitEvent(88)
EVENT_WIDGET_DEATH                                        = ConvertWidgetEvent(89)
EVENT_DIALOG_BUTTON_CLICK                                 = ConvertDialogEvent(90)
EVENT_DIALOG_CLICK                                        = ConvertDialogEvent(91)
-- ===================================================
--  Frozen Throne Expansion Events
--  Need to be added here to preserve compat
-- ===================================================
-- ===================================================
--  For use with TriggerRegisterGameEvent
-- ===================================================
EVENT_GAME_LOADED                                         = ConvertGameEvent(256)
EVENT_GAME_TOURNAMENT_FINISH_SOON                         = ConvertGameEvent(257)
EVENT_GAME_TOURNAMENT_FINISH_NOW                          = ConvertGameEvent(258)
EVENT_GAME_SAVE                                           = ConvertGameEvent(259)
EVENT_GAME_CUSTOM_UI_FRAME                                = ConvertGameEvent(310)
-- ===================================================
--  For use with TriggerRegisterPlayerEvent
-- ===================================================
EVENT_PLAYER_ARROW_LEFT_DOWN                              = ConvertPlayerEvent(261)
EVENT_PLAYER_ARROW_LEFT_UP                                = ConvertPlayerEvent(262)
EVENT_PLAYER_ARROW_RIGHT_DOWN                             = ConvertPlayerEvent(263)
EVENT_PLAYER_ARROW_RIGHT_UP                               = ConvertPlayerEvent(264)
EVENT_PLAYER_ARROW_DOWN_DOWN                              = ConvertPlayerEvent(265)
EVENT_PLAYER_ARROW_DOWN_UP                                = ConvertPlayerEvent(266)
EVENT_PLAYER_ARROW_UP_DOWN                                = ConvertPlayerEvent(267)
EVENT_PLAYER_ARROW_UP_UP                                  = ConvertPlayerEvent(268)
EVENT_PLAYER_MOUSE_DOWN                                   = ConvertPlayerEvent(305)
EVENT_PLAYER_MOUSE_UP                                     = ConvertPlayerEvent(306)
EVENT_PLAYER_MOUSE_MOVE                                   = ConvertPlayerEvent(307)
EVENT_PLAYER_SYNC_DATA                                    = ConvertPlayerEvent(309)
EVENT_PLAYER_KEY                                          = ConvertPlayerEvent(311)
EVENT_PLAYER_KEY_DOWN                                     = ConvertPlayerEvent(312)
EVENT_PLAYER_KEY_UP                                       = ConvertPlayerEvent(313)
-- ===================================================
--  For use with TriggerRegisterPlayerUnitEvent
-- ===================================================
EVENT_PLAYER_UNIT_SELL                                    = ConvertPlayerUnitEvent(269)
EVENT_PLAYER_UNIT_CHANGE_OWNER                            = ConvertPlayerUnitEvent(270)
EVENT_PLAYER_UNIT_SELL_ITEM                               = ConvertPlayerUnitEvent(271)
EVENT_PLAYER_UNIT_SPELL_CHANNEL                           = ConvertPlayerUnitEvent(272)
EVENT_PLAYER_UNIT_SPELL_CAST                              = ConvertPlayerUnitEvent(273)
EVENT_PLAYER_UNIT_SPELL_EFFECT                            = ConvertPlayerUnitEvent(274)
EVENT_PLAYER_UNIT_SPELL_FINISH                            = ConvertPlayerUnitEvent(275)
EVENT_PLAYER_UNIT_SPELL_ENDCAST                           = ConvertPlayerUnitEvent(276)
EVENT_PLAYER_UNIT_PAWN_ITEM                               = ConvertPlayerUnitEvent(277)
EVENT_PLAYER_UNIT_STACK_ITEM                              = ConvertPlayerUnitEvent(319)
-- ===================================================
--  For use with TriggerRegisterUnitEvent
-- ===================================================
EVENT_UNIT_SELL                                           = ConvertUnitEvent(286)
EVENT_UNIT_CHANGE_OWNER                                   = ConvertUnitEvent(287)
EVENT_UNIT_SELL_ITEM                                      = ConvertUnitEvent(288)
EVENT_UNIT_SPELL_CHANNEL                                  = ConvertUnitEvent(289)
EVENT_UNIT_SPELL_CAST                                     = ConvertUnitEvent(290)
EVENT_UNIT_SPELL_EFFECT                                   = ConvertUnitEvent(291)
EVENT_UNIT_SPELL_FINISH                                   = ConvertUnitEvent(292)
EVENT_UNIT_SPELL_ENDCAST                                  = ConvertUnitEvent(293)
EVENT_UNIT_PAWN_ITEM                                      = ConvertUnitEvent(294)
EVENT_UNIT_STACK_ITEM                                     = ConvertUnitEvent(318)
-- ===================================================
--  Limit Event API constants
--  variable, player state, game state, and unit state events
--  ( do NOT change the order of these... )
-- ===================================================
LESS_THAN                                                 = ConvertLimitOp(0)
LESS_THAN_OR_EQUAL                                        = ConvertLimitOp(1)
EQUAL                                                     = ConvertLimitOp(2)
GREATER_THAN_OR_EQUAL                                     = ConvertLimitOp(3)
GREATER_THAN                                              = ConvertLimitOp(4)
NOT_EQUAL                                                 = ConvertLimitOp(5)
-- ===================================================
--  Unit Type Constants for use with IsUnitType()
-- ===================================================
UNIT_TYPE_HERO                                            = ConvertUnitType(0)
UNIT_TYPE_DEAD                                            = ConvertUnitType(1)
UNIT_TYPE_STRUCTURE                                       = ConvertUnitType(2)
UNIT_TYPE_FLYING                                          = ConvertUnitType(3)
UNIT_TYPE_GROUND                                          = ConvertUnitType(4)
UNIT_TYPE_ATTACKS_FLYING                                  = ConvertUnitType(5)
UNIT_TYPE_ATTACKS_GROUND                                  = ConvertUnitType(6)
UNIT_TYPE_MELEE_ATTACKER                                  = ConvertUnitType(7)
UNIT_TYPE_RANGED_ATTACKER                                 = ConvertUnitType(8)
UNIT_TYPE_GIANT                                           = ConvertUnitType(9)
UNIT_TYPE_SUMMONED                                        = ConvertUnitType(10)
UNIT_TYPE_STUNNED                                         = ConvertUnitType(11)
UNIT_TYPE_PLAGUED                                         = ConvertUnitType(12)
UNIT_TYPE_SNARED                                          = ConvertUnitType(13)
UNIT_TYPE_UNDEAD                                          = ConvertUnitType(14)
UNIT_TYPE_MECHANICAL                                      = ConvertUnitType(15)
UNIT_TYPE_PEON                                            = ConvertUnitType(16)
UNIT_TYPE_SAPPER                                          = ConvertUnitType(17)
UNIT_TYPE_TOWNHALL                                        = ConvertUnitType(18)
UNIT_TYPE_ANCIENT                                         = ConvertUnitType(19)
UNIT_TYPE_TAUREN                                          = ConvertUnitType(20)
UNIT_TYPE_POISONED                                        = ConvertUnitType(21)
UNIT_TYPE_POLYMORPHED                                     = ConvertUnitType(22)
UNIT_TYPE_SLEEPING                                        = ConvertUnitType(23)
UNIT_TYPE_RESISTANT                                       = ConvertUnitType(24)
UNIT_TYPE_ETHEREAL                                        = ConvertUnitType(25)
UNIT_TYPE_MAGIC_IMMUNE                                    = ConvertUnitType(26)
-- ===================================================
--  Unit Type Constants for use with ChooseRandomItemEx()
-- ===================================================
ITEM_TYPE_PERMANENT                                       = ConvertItemType(0)
ITEM_TYPE_CHARGED                                         = ConvertItemType(1)
ITEM_TYPE_POWERUP                                         = ConvertItemType(2)
ITEM_TYPE_ARTIFACT                                        = ConvertItemType(3)
ITEM_TYPE_PURCHASABLE                                     = ConvertItemType(4)
ITEM_TYPE_CAMPAIGN                                        = ConvertItemType(5)
ITEM_TYPE_MISCELLANEOUS                                   = ConvertItemType(6)
ITEM_TYPE_UNKNOWN                                         = ConvertItemType(7)
ITEM_TYPE_ANY                                             = ConvertItemType(8)
--  Deprecated, should use ITEM_TYPE_POWERUP
ITEM_TYPE_TOME                                            = ConvertItemType(2)
-- ===================================================
--  Animatable Camera Fields
-- ===================================================
CAMERA_FIELD_TARGET_DISTANCE                              = ConvertCameraField(0)
CAMERA_FIELD_FARZ                                         = ConvertCameraField(1)
CAMERA_FIELD_ANGLE_OF_ATTACK                              = ConvertCameraField(2)
CAMERA_FIELD_FIELD_OF_VIEW                                = ConvertCameraField(3)
CAMERA_FIELD_ROLL                                         = ConvertCameraField(4)
CAMERA_FIELD_ROTATION                                     = ConvertCameraField(5)
CAMERA_FIELD_ZOFFSET                                      = ConvertCameraField(6)
CAMERA_FIELD_NEARZ                                        = ConvertCameraField(7)
CAMERA_FIELD_LOCAL_PITCH                                  = ConvertCameraField(8)
CAMERA_FIELD_LOCAL_YAW                                    = ConvertCameraField(9)
CAMERA_FIELD_LOCAL_ROLL                                   = ConvertCameraField(10)
BLEND_MODE_NONE                                           = ConvertBlendMode(0)
BLEND_MODE_DONT_CARE                                      = ConvertBlendMode(0)
BLEND_MODE_KEYALPHA                                       = ConvertBlendMode(1)
BLEND_MODE_BLEND                                          = ConvertBlendMode(2)
BLEND_MODE_ADDITIVE                                       = ConvertBlendMode(3)
BLEND_MODE_MODULATE                                       = ConvertBlendMode(4)
BLEND_MODE_MODULATE_2X                                    = ConvertBlendMode(5)
RARITY_FREQUENT                                           = ConvertRarityControl(0)
RARITY_RARE                                               = ConvertRarityControl(1)
TEXMAP_FLAG_NONE                                          = ConvertTexMapFlags(0)
TEXMAP_FLAG_WRAP_U                                        = ConvertTexMapFlags(1)
TEXMAP_FLAG_WRAP_V                                        = ConvertTexMapFlags(2)
TEXMAP_FLAG_WRAP_UV                                       = ConvertTexMapFlags(3)
FOG_OF_WAR_MASKED                                         = ConvertFogState(1)
FOG_OF_WAR_FOGGED                                         = ConvertFogState(2)
FOG_OF_WAR_VISIBLE                                        = ConvertFogState(4)
-- ===================================================
--  Camera Margin constants for use with GetCameraMargin
-- ===================================================
CAMERA_MARGIN_LEFT                                        = 0
CAMERA_MARGIN_RIGHT                                       = 1
CAMERA_MARGIN_TOP                                         = 2
CAMERA_MARGIN_BOTTOM                                      = 3
-- ===================================================
--  Effect API constants
-- ===================================================
EFFECT_TYPE_EFFECT                                        = ConvertEffectType(0)
EFFECT_TYPE_TARGET                                        = ConvertEffectType(1)
EFFECT_TYPE_CASTER                                        = ConvertEffectType(2)
EFFECT_TYPE_SPECIAL                                       = ConvertEffectType(3)
EFFECT_TYPE_AREA_EFFECT                                   = ConvertEffectType(4)
EFFECT_TYPE_MISSILE                                       = ConvertEffectType(5)
EFFECT_TYPE_LIGHTNING                                     = ConvertEffectType(6)
SOUND_TYPE_EFFECT                                         = ConvertSoundType(0)
SOUND_TYPE_EFFECT_LOOPED                                  = ConvertSoundType(1)